# This is a basic workflow to help you get started with Actions

name: Run test suite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.8
        - 3.9
          
    name: Check Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: pip install --upgrade pip

    - name: Install package
      run: python -m pip install -e .[test]

    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m pytest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3.1.0
